### ISSUE TITLE
Could you add results obtained from demo.fasta for each tool?

### ISSUE THREAD

**Issue by ryotag** [DerKevinRiehl/transposon_annotation_tools#10]
Thank you for providing bioconda packages on  transposon detection tools!

I'm interested in MITEs and using mite detection tools, including MiteTracker and MiteFinderII, which were installed using conda.
However, I'm not sure whether I could successfully install these tools.
For example, I found that `miteFinderII -input demo.fasta -output result.txt` (the code listed in README) returned an empty file, though I could get a reasonable result when I lowered the threshold using `-threshold` option.
It would be nice if you could provide results on demo.fasta obtained using each tool in this repo for our references.

**Comment by DerKevinRiehl** [comment]
Dear Ryotag,
thanks for your interest.
If you have a look at reasonaTE, a pipeline that calls all tools from this repository, there are exemplary outputs from the tools for the demo.fasta:
https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/tree/main/workspace/testProject

Best, Kevin

**Comment by ryotag** [comment]
Dear Kevin,

Thank you very much for letting me know that!

Best regards,
