### ISSUE TITLE
The output results from helitronscanner

### ISSUE THREAD

**Issue by Niohuruzh** [DerKevinRiehl/transposon_annotation_tools#4]

**Comment by Niohuruzh** [comment]
Hi DerKevinRiehl
I use `helitronscanner` command as described in code, it work successfully. However, I'm so confused about the output.txt. It looks like this:

>
>Chr1
495946:509834 [6:7] 2207551:2216246 [7:5] 2464584:2469957 [6:5] 
>Chr10
296181:305004 [6:8] 523700:534809 [6:5] 
>Chr11
305074:306749 [6:5] 
>Chr12
270608:279619 [6:5] 
>Chr13
862025:881824 [7:6][862331:7] 
>Chr14
>Chr15
>Chr16
>Chr17
119114:122742 [6:5] 488696:508040 [6:9] 
>Chr18
508608:516817 [7:5] 
>Chr2
1026336:1034307 [6:5] 
>Chr3
>Chr4
>Chr5
1676003:1679124 [7:5] 
>Chr6
>Chr7
134159:136156 [6:5] 1169003:1172486 [6:7] 1304878:1316211 [5:5] 
>Chr8
336856:356775 [7:6] 
>Chr9

I have no idea about the information in [ ] 
Is there any information file for the output.txt?

**Comment by DerKevinRiehl** [comment]
Dear Niohuruzh,
first of all I am very happy to see your interest in our software package.

To your question, for the interpretation of the outputs:
```
Chr6
Chr7
134159:136156 [6:5] 1169003:1172486 [6:7] 1304878:1316211 [5:5]
```
Means:
- There is nothing found in Chr6
- There are three helitrons found on Chr7, with the given coordinates in BP "134159:136156", "1169003:1172486" and "1304878:1316211"
- The number in the brackets (from my perspective) represent confidence levels (so how confident the software is about finding the helitrons there). (the higher the number / ratio / fraction, the more confident)

Unfortunately, as you might have read on the page, this is a collection of renowned and established transposon annotation tools, but packaged and migrated to conda. I am not the author of HelitronScanner, and unfortunately the original paper also doesnt explain it too much, but from reading the software code it is my interpretation.

Still, I hope that these explanations could guide you somehow.

Also, I want to emphasize that the transposon annotation tools are part of a bigger software project called "[TransposonUltimaTE](https://github.com/DerKevinRiehl/TransposonUltimate)". As it seems, you are interested in annotation of transposons, if so, check out [reasonaTE](https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE). This is a tool that combines the knowledge of many different annotation tools.

Looking forward to your answer, further questions, and maybe even for a star on Github ;-) ,
Best regards,
Kevin Riehl

**Comment by Niohuruzh** [comment]
Dear Kevin Riehl,
First of all, thanks for your quick reply. And your explanation about the output file is so helpful for me.
Second, thanks for your recommendation for transposon detection tools. For me, one gene is multi-copied in my diploid strains which should be two copies. Therefore, I want to know the gene whether is influenced by transposon elements. However, I'm not an expert in transposon study, so it's hard for me to understand that phenomenon. So I believe these tools will help me a lot in my future work.

Best regards,
Niohuruzh

**Comment by DerKevinRiehl** [comment]
Great to hear Niohuruzh,
please do not hesitate to ask further questions if you have any.

Best regards,
Kevin Riehl
