### ISSUE TITLE
issue in the perl package_ Transposon Annotation Tools

### ISSUE THREAD

**Issue by Ramkyeri** [DerKevinRiehl/transposon_annotation_tools#5]
Dear Kevin,  thank you for your reply.  I tried to install [Transposon Annotation Tools]. First few comments were fine,   i got error while running, mamba install -y -c derkevinriehl transposon_annotation_tools_mustv2

Problem: package perl-bio-searchio-hmmer-1.7.3-pl5321hdfd78af_0 requires perl >=5.32.1,<6.0a0 *_perl5, but none of the providers can be installed

![image](https://user-images.githubusercontent.com/70749594/159712434-069086c0-7d24-45c6-8a3a-433da5229fe7.png)

with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Kevin,  I also checked perl version,  it has version 5.32.1,  but I do not know why I am getting error

![Uploading image.png…]()

**Comment by DerKevinRiehl** [comment]
Dear Ramky,
could you be more spocific on your Operating System and Hardware / Cluster you are using?
I guess a LINUX ?

As you are located in China, do you use a VPN to install or just normal internet?

Best,
Kevin

**Comment by DerKevinRiehl** [comment]
I put your questions from the mail here to answer.

**2. Transposon Classifier "RFSB" (this was successfully installed and no need to specify the python
 package, but I have to try with Moso bamboo genome)** 
Well, you do not need, as our tool is able to classify any Transposon Sequence. You just need to give a FASTA file with Transposons as input, and RFSB will classify all sequences.

**3. Transposon Annotator "reasonaTE" (This is a main tool to generate TE GFF,  but before installing this tool,  i have to install RepeatMasker" and "RepeatModeler,   but I don't how to install these two in Linux)
I will be grateful if you share the script for installing RepeatMasker" and "RepeatModeler.** 
RepeatMasker and RepeatModeler are one of the most frequently used tools in Transposon analysis out there. However, installing them is quite tricky and massively depends on your software and hardware setup. As we are not the developers of these tools, we can hardly help you on that. Besides online research on how to install it, we recommend you to ask some bioinformatician of your department, he probably can help you to set it up.
You can try to follow this tutorial:
https://supcom.hgc.jp/english/utili_info/manual/RepeatMasker.html
Or the official guideline from the authors of RepeatMasker and RepeatModeler:
https://www.repeatmasker.org/RepeatModeler/
https://www.repeatmasker.org/RepeatMasker/

**4. Transposition Event Detector "deTEct" (I want to use this also,  but  what is the meaning of this,  sequenced probe genome reads. We have both long reads and short reads).** 
As you can see in our page for "deTEct" you need:
Input: Structural variants (VCF file) of [PBSV](https://github.com/PacificBiosciences/pbsv) (on [PBMM2](https://github.com/PacificBiosciences/pbmm2) alignments) or [Sniffles](https://github.com/fritzsedlazeck/Sniffles) (on [NGMLR](https://github.com/philres/ngmlr) alignments), transposon annotations (by [resonaTE](https://github.com/DerKevinRiehl/transposon_annotation_resonaTE)), reference genome (FASTA)

Please find our GitHub pages for all tools:
https://github.com/DerKevinRiehl/transposition_detector_deTEct
https://github.com/DerKevinRiehl/TransposonUltimate

Happy to help you with any further questions,
Best regards,
Kevin

**Comment by Ramkyeri** [comment]
> Dear Ramky, could you be more spocific on your Operating System and Hardware / Cluster you are using? I guess a LINUX ?
> 
> As you are located in China, do you use a VPN to install or just normal internet?
> 
> Best, Kevin

Dear Kevin, 
Many thanks for your reply.  I use Linux (WSL2  installed on windows).  Windows Subsystem for Linux with the command. Using WSL2,  I successfully run TEtranscripts, TEcount,  TEsmall,  etc. 

 currently I am in China,  I used just normal internet,   infact, sometime, I use   Veepeen

with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Kevin,
Many thanks for your detailed reply and sending me the tutorial.  As per your suggestion,  i will install RepeatMasker and RepeatModeler. 

with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Kevin,  

I solved the issue.   instead of using "Installation using mamba (recommended)", I used "Installation using conda". I did not get any error. However, it took little time, 

To run complete Transposon Annotation Tools, I have to use "transposonPSI" comment,  am i correct?  

![image](https://user-images.githubusercontent.com/70749594/160129730-f8879489-fbba-47d3-ae9f-253bfd59127e.png)

![image](https://user-images.githubusercontent.com/70749594/160128448-6f2406ed-2fbd-4021-9bdf-197264087e4e.png)

However, still I need to install RepeatMasker" and "RepeatModeler. 

with regards

**Comment by DerKevinRiehl** [comment]
Dear Ramkyeri,
thats great news!
Hope you will progress even more soon. If you start with these tools, you need to invest some time in installing and be patient, but it will pay out :-).

So transposon annotation tools is a collection of annotation tools.
TransposonPSI is only one of many tools. 
You can find a list of tools and papers that explain what they are used for here:
https://github.com/DerKevinRiehl/transposon_annotation_tools

Best of luck and success,
looking forward for further updates from your side,
Best, Kevin

**Comment by Ramkyeri** [comment]
Dear Kevin, 

Thank you,  I got it   transposon_annotation_tools is collection of tools, but these tools can be run individually, but not combined. 

with regards, 

Ramky
